version: "3.8"

services:
  # =========================
  # Base de datos SQL Server
  # =========================
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: credit-sql
    environment:
      - SA_PASSWORD=Your_password123!       # contraseña 
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"                         # expone SQL en localhost:1433
    volumes:
      - ./sql:/docker-entrypoint-initdb.d   # montamos tu carpeta /sql con scripts
      - mssql_data:/var/opt/mssql           # datos persistentes de SQL Server
    
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123!", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ===========  
  # API (C#)  
  # ===========  
  api:
    build: ./backend/CreditApi
    container_name: credit-api
    ports:
      - "5131:80"                           # http://localhost:5131 -> puerto 80 del contenedor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sql                                  # arranca api después de sql

  # ==========================  
  # Frontend (React + NGINX)  
  # ==========================  
  web:
    build: ./frontend
    container_name: credit-web
    ports:
      - "5173:80"                           # http://localhost:5173
    depends_on:
      - api

  # ==========================  
  # ML Service (Python + FastAPI)  
  # ==========================  
  ml-service:
    build: ./ml-service
    container_name: credit-ml
    depends_on:
      - sql
    ports:
      - "8000:8000"                         # http://localhost:8000/docs
    environment:
      - PYTHONUNBUFFERED=1

# ===========  
# Volúmenes  
# ===========  
volumes:
  mssql_data:
